### ISSUE TITLE
Widget not resizable in width

### ISSUE THREAD

**Issue by lorenzovngl** [w2sv/WiFi-Widget#2]
Hi,
I installed the app on my device with Android 13, but I encountered the following situation.

![photo_2023-02-04_15-25-40](https://user-images.githubusercontent.com/13767301/216772914-cbee9885-5ff9-4360-8436-1f470a8561af.jpg)

I can't resize the widget to make it larger, in fact there is no blue dot on the left and right borders. This, as you can see, causes the break of the labels on the left.

**Comment by w2sv** [comment]
Damn, that really looks awful :D
Yeah, I had previously disabled horizontal resizing, as the width was spot on on all of my test devices, so that I didn't see why one would want to change it. I changed that in version [1.1.2](https://github.com/w2sv/WiFi-Widget/releases/tag/1.1.2) now, though. Let me know if you keep encountering any issues there. 

Thanks a bunch for pointing that out to me!

**Comment by lorenzovngl** [comment]
Now it works perfectly, thank you!
![photo_2023-02-05_21-43-16](https://user-images.githubusercontent.com/13767301/216844899-4651103f-69dc-48d1-84fe-d7707ce15a58.jpg)
