### ISSUE TITLE
F-Droid build failed

### ISSUE THREAD

**Issue by linsui** [w2sv/WiFi-Widget#60]
```
> Task :app:lintVitalRelease FAILED
/builds/fdroid/fdroiddata/build/com.wa2c.android.cifsdocumentsprovider/app/src/main/AndroidManifest.xml:21: Error: MainActivity must extend android.app.Activity [Instantiatable]
            android:name=".presentation.ui.MainActivity"
                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   Explanation for issues of type "Instantiatable":
   Activities, services, broadcast receivers etc. registered in the manifest
   file (or for custom views, in a layout file) must be "instantiatable" by
   the system, which means that the class must be public, it must have an
   empty public constructor, and if it's an inner class, it must be a static
   inner class.
1 errors, 0 warnings
> Task :app:mergeDexRelease
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':app:lintVitalRelease'.
> Lint found fatal errors while assembling a release target.
  
  Fix the issues identified by lint, or create a baseline to see only new errors.
```

Could you please take a look?

**Comment by w2sv** [comment]
I don't think that's the right log. That's a completely different package name in there.

**Comment by w2sv** [comment]
I've created a new release which resolves the issue I presume to be behind the failing build anyways. I don't know where to find the log that features the actual error message.

**Comment by linsui** [comment]
Sorry, my mistake...

**Comment by linsui** [comment]
For builds in the buildserver, see https://monitor.f-droid.org/builds.

**Comment by w2sv** [comment]
Thank you.

**Comment by licaon-kter** [comment]
@w2sv please build future release APKs from the actual Tagged commit, eg: for  https://github.com/w2sv/WiFi-Widget/releases/tag/1.4.14 -> https://github.com/w2sv/WiFi-Widget/commit/c5a31ba7aeb82f6372bdd5ba1fa15d1208909707

Current APK was build from cd78d31b01c4defd5dc5b7f813798ded54562287 instead, as seen: https://gitlab.com/fdroid/fdroiddata/-/jobs/6694088780#L4565

I've fixed in in F-Droid now, so no need to do anything: https://gitlab.com/fdroid/fdroiddata/-/commit/adf6d5e534d58ccb3c89192ee39ccc070ef6a637

**Comment by w2sv** [comment]
Yeah sorry, that was an accident. I'll do my best to prevent that in the future. Thank you for the fix.
